#!/bin/sh

# Defaults
SWIFT_END_POINT="https://swift.org/builds/ubuntu1510/swift-2.2-SNAPSHOT-2016-01-11-a/"
SWIFT_VERSION="swift-2.2-SNAPSHOT-2016-01-11-a-ubuntu15.10"
SWIFT_SNAPSHOT_LOCATION="/usr/local/swiftsnapshot"
SWIFT_LOCAL_LOCATION=${SWIFT_SNAPSHOT_LOCATION}/${SWIFT_VERSION}
# swift and PerfectLib dependencies
echo "Installing Dependencies..."
sudo apt-get -y install clang libicu-dev
sudo apt-get -y install clang libssl-dev
sudo apt-get -y install clang libevent-dev
sudo apt-get -y install clang libsqlite3-dev

# download and verify swift
echo "Downloading Swift..."
wget ${SWIFT_END_POINT}/${SWIFT_VERSION}.tar.gz -P ${SWIFT_SNAPSHOT_LOCATION}
wget ${SWIFT_END_POINT}/${SWIFT_VERSION}.tar.gz.sig -P ${SWIFT_SNAPSHOT_LOCATION}
wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -

echo "Verifying Swift..."
gpg --keyserver hkp://pool.sks-keyservers.net --refresh-keys Swift
gpg --verify ${SWIFT_LOCAL_LOCATION}.tar.gztar.gz.sig

# TODO: Abort if previous step fails

# Extracting and linking swift 
echo "Extracting and Linking swift..."
tar xzf ${SWIFT_LOCAL_LOCATION}.tar.gz
export PATH=${SWIFT_LOCAL_LOCATION}/usr/bin:"${PATH}"

# building PerfectLib
echo "Building PerfectLib..."
cd PerfectLib
make 
sudo make install
# cleaning up
sudo clean
sudo rm -fr tmp
# building PerfectServer
echo "Building PerfectServer..."
cd ../PerfectServer
make
ln -s perfectserverfcgi /usr/local/bin/perfectserverfcgi
ln -s perfectserverhttp /usr/local/bin/perfectserverhttp
mkdir -p /usr/local/swiftserver/PerfectLibraries
